# Generated by Django 5.0.3 on 2024-06-08 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dba',
            },
        ),
        migrations.CreateModel(
            name='DBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=50)),
                ('Account_No', models.CharField(max_length=14, unique=True)),
                ('CIF_No', models.CharField(max_length=25)),
                ('Branch_Code', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=25)),
                ('Repeat_pwd', models.CharField(max_length=25)),
                ('Facility_Required', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('Registered_Mobile_No', models.CharField(max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'dbc',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tpin', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='transfers.dbc')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='transfers.dbc')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
